#!/bin/sh
set -e

cd "$(dirname "$0")"
distro=$(python distro.py)

#Shell can't do string comparosin like bash so doing it awkwardly:
centos=$(echo $distro | grep -ic -e centos -e redhat -e fedora || true)
ubuntu=$(echo $distro | grep -ic -e ubuntu -e debian || true)
debian=$(echo $distro | grep -ic debian || true)
fedora=$(echo $distro | grep -ic fedora || true)

if [ $ubuntu -gt 0 ]; then
    
    for package in ruby1.9.1 ruby1.9.1-dev build-essential; do
        if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
            # add a space after old values
            missing="${missing:+$missing }$package"
        fi
    done
    if [ -n "$missing" ]; then
        echo "$0: installing missing required packages: $missing" 1>&2
        sudo apt-get update
        sudo \
	    env DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical \
	    apt-get \
	    -q \
	    -o Dpkg::Options::=--force-confnew \
	    install \
	    --no-install-recommends \
	    --assume-yes \
	    -- \
	    $missing
    fi

    CHEF_BIN_DIR="${HOME}/.gem/ruby/1.9.1/bin"
    CHEF_BIN="$CHEF_BIN_DIR/chef-solo"
    if [ $debian -gt 0 ]
    then
        sudo sed -i 's/^\# en_US/en_US/g' /etc/locale.gen || true
        sudo /usr/sbin/locale-gen en_US.UTF-8 || true
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US.UTF-8
        export LC_ALL=en_US.UTF-8
        gem1.9.1 install --no-rdoc --no-ri mime-types -v "<2.0
    fi
    if [ ! -e "$CHEF_BIN" ]; then
        gem1.9.1 install --no-rdoc --no-ri --user-install chef
    fi
    if [ $debian -gt 0 ]
    then
        sudo -E "$CHEF_BIN" -c solo.rb -j solo.json
    else
        sudo "$CHEF_BIN" -c solo.rb -j solo.json
    fi
fi

if [ $centos -gt 0 ]; then
    if [ $fedora -lt 1 ]
    then
        # EPEL Repo
        installed=$(sudo yum list installed | grep -ic epel-release- || true)
        if [ $installed -eq 0 ]; then
            sudo yum -y install http://mirrors.tummy.com/pub/fedora.redhat.com/epel/6/x86_64/epel-release-6-8.noarch.rpm
        fi
    fi
    if [ $fedora -gt 0 ]
    then
        sudo yum -y install audit
    fi

    # Group Packages:
    for grouppackage in "Development Tools"; do
        installed=$(sudo yum grouplist | grep -A 100 "Installed Groups" | grep -B 100 "Installed Language Groups" | egrep "^   " | grep -ic "$grouppackage" || true)
        if [ $installed -eq 0 ]
        then
            echo installing missing group package: "$grouppackage"
            sudo yum --nogpgcheck -y groupinstall "$grouppackage"
        fi
    done

    # Individual Packages
    for package in gcc make automake ruby-devel ruby rubygems; do
        installed=$(sudo yum list installed | grep -ic "^$package\." || true)
        if [ $installed -eq 0 ]; then
            echo Installing missing package: "$package"
            sudo yum --nogpgcheck -y install "$package"
        fi
    done

    rubyversion=$(ruby -v | awk '{print $2}' | cut -d'.' -f1-2)
    if [ $fedora -gt 0 ]
    then
        CHEF_BIN="/usr/local/bin/chef-solo"
    else
        CHEF_BIN="/usr/bin/chef-solo"
    fi

    if [ ! -e "$CHEF_BIN" ]; then
        #Mime-types 2.0 requires ruby 1.9.2 which is not included on RHEL/centos.
        #Pre-install 1.25 so it doesn't attempt to grab 2.0 as a dependency.
        sudo gem install --no-rdoc --no-ri mime-types -v "<2.0"
        sudo gem install --no-rdoc --no-ri chef
    fi

    sudo "$CHEF_BIN" -l debug -c solo.rb -j solo.json
fi
