#!/bin/sh

# This file is not chmod a+x on purpose, to avoid running it
# accidentally. Automation will always run it through "wget -q -O-
# ... | sh"

set -e

for package in git; do
    if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
        # add a space after old values
        missing="${missing:+$missing }$package"
    fi
done
if [ -n "$missing" ]; then
    echo "$0: installing missing required packages: $missing" 1>&2
    sudo \
	env DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical \
	apt-get \
	-q \
        -o Dpkg::Options::=--force-confnew \
        install \
        --no-install-recommends \
        --assume-yes \
	-- \
	$missing
fi

SCRATCH="$(mktemp -d 'solo-from-scratch.')"
cd "$SCRATCH"
git init
git pull https://github.com/NewDreamNetwork/ceph-qa-chef.git
./solo/run
